resolver: lts-9.10

packages: 
  - .
  - batchd-core/
  - batchd-docker/
  - batchd-libvirt/
  - batchd-amazonka/

# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps: 
  - optparse-applicative-0.14.0.0
  - dates-0.2.2.1
  - docker-0.4.1.1
  - libvirt-hs-0.2.1
  - libssh2-0.2.0.5
  - libssh2-conduit-0.2.1
  - hsyslog-5
  - select-0.4.0.1
  - monad-metrics-0.2.1.0
  - haskell-gettext-0.1.1.0
  - text-format-heavy-0.1.5.0
  - localize-0.2.0.0
  - heavy-logger-0.3.1.0
  - heavy-logger-amazon-0.1.0.0

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

