resolver: lts-9.10

packages: 
  - .
  - batchd-core/
  - batchd-docker/
  - batchd-libvirt/
  - batchd-amazonka/
  - location:
      git: https://github.com/portnov/libssh2-hs.git
      commit: master
    extra-dep: true
    subdirs: [libssh2]
  - location:
      git: https://github.com/portnov/heavy-logger.git
      commit: 67b86f4
    subdirs: [., heavy-logger-amazon]
    extra-dep: true
  - location:
      git: https://github.com/portnov/localize.git
      commit: master
    extra-dep: true

# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps: 
  - dates-0.2.2.1
  - docker-0.4.1.1
  - libvirt-hs-0.2.1
  - hsyslog-5
  - select-0.4.0.1
  - haskell-gettext-0.1.1.0
  - text-format-heavy-0.1.5.0

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

